module.exports.config = {
  exportPath: "./_build/css/",
  variablesBase: 'base',
  colors: {
    primary: '',
    secondary: '',
    success: '',
    danger: '',
    warning: '',
    info: '',
    primaryLight: '',
    secondaryLight: '',
    successLight: '',
    dangerLight: '',
    warningLight: '',
    infoLight: '',
    primary20: '',
    secondary20: '',
    success20: '',
    danger20: '',
    warning20: '',
    info20: '',
    primary50: '',
    secondary50: '',
    success50: '',
    danger50: '',
    warning50: '',
    info50: '',
    focus: '',
  },
  systemMargin: '',
  systemHeight: '',
  systemBorder: '',
  sidebarWidth: '',
  darkMode: {},
  reset: {},
  base: {},
  typography: {},
  layout: {},
  components: {},
  forms: {},
  utilities: {},
//  u_mpNonsystem: {},
  attributes: {},
}