
module.exports.config = {
  colors: {
    primary: "default",
    secondary: "default",
    success: "default",
    danger: "default",
    warning: "default",
    info: "default",
    primaryLight: "default",
    secondaryLight: "default",
    successLight: "default",
    dangerLight: "default",
    warningLight: "default",
    infoLight: "default",
    primary20: "default",
    secondary20: "default",
    success20: "default",
    danger20: "default",
    warning20: "default",
    info20: "default",
    primary50: "default",
    secondary50: "default",
    success50: "default",
    danger50: "default",
    warning50: "default",
    info50: "default",
    focus: "default",
  },
  systemMargin: "default",
  systemHeight: "default",
  systemBorder: "default",
  darkMode: {},
  reset: {},
  base: {},
  typography: {},
  layout: {},
  components: {},
  forms: {},
  utilities: {},
//  u_mpNonsystem: {},
  attributes: {},
}